# Generated by Django 3.0.6 on 2020-05-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champselect', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='DropDown',
        ),
    ]
